import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import Navbar05Page from "@/components/navbar-05/navbar-05";

const sarabun = Sarabun ({
  subsets: ['thai'],
  weight: ['100','200','300','400','500','600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sarabun.className} antialiased`} >
        <Navbar05Page/>
        {children}
      </body>
    </html>
  );
}
